# Generated by Django 4.0.3 on 2022-03-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
