# Generated by Django 4.0.3 on 2022-03-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='available',
            new_name='visible',
        ),
    ]
